name: .NET

on:
  push:
    branches: [ Development ]
  pull_request:
    branches: [ Development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
        dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish  
      run: dotnet publish Qwirkle.Web.Api -c Release -r linux-x64 --self-contained true /p:UseAppHost=true
    - name: Archive build

      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: publish
        path: publish

    - name: Build site assets
      working-directory: ${{ github.workspace }}
      run: ls -la
      
